# Generated by Django 4.0.7 on 2022-09-14 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='anni_id',
            field=models.ForeignKey(blank=True, db_column='anni_id', on_delete=django.db.models.deletion.CASCADE, to='letters.anniversary'),
        ),
    ]
