# Generated by Django 4.0.7 on 2022-09-14 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='file',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='letter',
            name='text',
            field=models.CharField(max_length=255),
        ),
    ]
