# Generated by Django 4.0.7 on 2022-09-14 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0003_alter_letter_file_alter_letter_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anniversary',
            name='date',
            field=models.DateField(),
        ),
    ]
